from .image_classification import ImageClassification
from .image_segmentation import ImageSegmentation
from .facial_landmark_detection import FacialLandmarkDetection
from .video_classification import VideoClassification
